@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package com.supercat765.mumboredstone;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;
